### ISSUE TITLE
[1.12.2] Game crash when i open any inventory from any mods/vanilla.

### ISSUE THREAD

**Issue by Mrthomas20121** [YaLTeR/MouseTweaks#48] opened 2021-03-31 10:37 UTC
Every times i open any inventory with mouse tweak installed it just crash.
yes that is a modpack. 
i do not know which mod cause that crash but i am certain it is not mousetweaks because mousetweaks work just fine on its own with just forge and jei.

i will eventually found which mod is causing this, just letting you know there is a crash.

Mouse tweak version: 2.10
Crash report : https://pastebin.com/DGYSbGen

**Comment by YaLTeR** [comment] 2021-03-31 12:19
I'm really not sure what this is caused by, my guess is some other mod bundled what it shouldn't have.

**Comment by Mrthomas20121** [comment] 2021-03-31 12:42
looking at the log it crashing during a tick event
Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$RenderTickEvent@57cee254:
i was able to identify a mod. i'm testing without that mod to see if that mod is the cause.

**Comment by Mrthomas20121** [comment] 2021-03-31 15:58
probably the case, the only mod i know that does it is Wireless crafting thermal but i don't have that mod installed

**Comment by YaLTeR** [comment] 2021-05-08 18:39
Closing as this is likely not a mouse tweaks issue.

**Closed by YaLTeR** 2021-05-08 18:39 UTC
Labels: question
